### ISSUE TITLE
Mark TagNumber and BirthDate as NOT NULL in the Python script that generates the database file.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [Camoen/CattleLog#3]
The script we use to generate the `.db` file does not mark these two columns as `NOT NULL`, but they form the primary key of the `cattle` table and thus cannot be null. This creates some issues when trying to load the database file into Room:

![image](https://user-images.githubusercontent.com/19352442/64860221-7d2aad80-d5fa-11e9-9ef1-fdac0258bb17.png)

I was able to get around those temporarily by just modifying the `.db` file using DB Browser for SQLite and setting the two columns to be `NOT NULL`. However, we will need to update this in the script itself.

**Comment by Camoen** [comment]
Should be fixed.
