### ISSUE TITLE
Fix database download on initial install and automatic updating functionality.

### ISSUE THREAD

**Issue by Camoen** [Camoen/CattleLog#32]
In the `onCreate` function in `CattleLog/app/src/main/java/com/example/cattlelog/main_activity/MainActivity.kt`, we currently need to (1) comment out these lines to successfully run the app on a new device (fresh install):

```
        val sectionsPagerAdapter =
            TabPagerAdapter(this, supportFragmentManager)
        val viewPager: ViewPager = findViewById(R.id.view_pager)
        viewPager.adapter = sectionsPagerAdapter
        val tabs: TabLayout = findViewById(R.id.tabs)
        tabs.setupWithViewPager(viewPager)
```

(2) After these lines are commented out, we must place this line of code (I generally place it directly after the commented out block):
`setDatabaseVersion(false)`

At this point, the fresh install will appropriately download a fresh database file if required.**  At this point, uncomment the 6 lines in the block above, run the app again, and it will function as expected.

**I believe that this placement of `setDatabaseVersion(false)` will also trigger the download of a fresh database file for devices that already have the app installed.  I am unsure if this is the best place to call `setDatabaseVersion(false)`, or if we should also call it in an `onResume` (or similar) function. 
**Note: Even though a fresh database file is downloaded and placed in the app's internal storage (under the `files` directory, which is a sibling to the `databases` directory), the database itself is not recreated, so the data displayed in the app is out of date.**

**Comment by AleksandrHovhannisyan** [comment]
> comment out these lines to successfully run the app on a new device (fresh install):

That part concerns me. How are we going to get this to work for the first-time install on the end-user devices?
